apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-monitor-extension
  labels:
    app: "zen-adv"
    icpdata_addon: "true"
    icpdata_addon_version: "4.3.0"
    release: "zen-adv"
data:
  extensions: |
      [
      {
          "extension_point_id": "zen_alert_monitor",
          "extension_name": "zen_alert_monitor_sample",
          "display_name": "Sample alert monitor",
          "details": {
            "name":"sample-monitor",
            "image": "image-registry.openshift-image-registry.svc:5000/zen63/sample-monitor:v1",
            "schedule": "*/10 * * * *",
            "event_types": [
              {
                "name": "check-custom-pvc-status",
                "alert_type": "platform",
                "description": "Unbound or failed PVC.",
                "resolution": "Check PVC logs."
              }
            ]
          }
        }
      ]