apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-monitor-extension
  labels:
    app: "zen-adv"
    icpdata_addon: "true"
    icpdata_addon_version: "4.4.0"
    release: "zen-adv"
data:
  extensions: |
      [
      {
          "extension_point_id": "zen_alert_monitor",
          "extension_name": "platform_monitor",
          "display_name": "Platform monitor",
          "details": {
            "name":"platform",
            "description": "platform monitor description",
            "image": "image-registry.openshift-image-registry.svc:5000/zentwo/pvc-monitor:v1",
            "schedule": "*/10 * * * *",
            "event_types": [
              {
                "name": "check-volume-status",
                "simple_name": "Volume usage status check",
                "alert_type": "platform",
                "short_description": "Monitors volume usage for PVCs.",
                "long_description": "Current Usage: <Usage> | Total Usage: <Total> | Usage Percentage: <UsagePct>",
                "url": "/platformManagement/monitoring/pods",
                "url_title": "View volume usage", 
                "web_link": "Check volume usage.",
                "reason_code_prefix": "11"
              }
            ]
          }
        }
      ]