apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-monitor-extension
  labels:
    app: "zen-adv"
    icpdata_addon: "true"
    icpdata_addon_version: "4.3.0"
    release: "zen-adv"
data:
  extensions: |
    [
      {
        "extension_point_id": "zen_alert_profile",
        "extension_name": "zen_alert_profile_default",
        "display_name": "Default alert profile",
        "details": {
          "name": "default",
          "description": "Default alert profile which enables all possible alerts, as long as the respective configuration details are provided via endpoints.",
          "alerts": {
            "smtp": true,
            "snmp": true,
            "slack": true
          },
          "smtp":{
            "registered_email_ids": []
          }
        }
      }
    ]