apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-alert-type-extension
  labels:
    icpdata_addon: "true"
    icpdata_addon_version: "4.3.0"
data:
  extensions: |
    [
      {
        "extension_point_id": "zen_alert_type",
        "extension_name": "sample_alert_type",
        "display_name": "Sample alert type",
        "details": {
          "name": "sample-alert-type",
          "description": "defines rules for alerting on sample monitors",
          "rules": {
            "critical": { 
              "trigger_type": "custom",
              "alert_count": 3,
              "alert_over_count": 3,
              "snooze_time": 12,
              "notify_when_condition_clears": true
            }, 
            "warning": { 
              "trigger_type": "custom",
              "alert_count": 5,
              "alert_over_count": 20,
              "snooze_time": 24
            }
          }
        }
      }
    ]